<a href="https://colab.research.google.com/github/mohamadga04/GeostatisticsLessonsNotebooks/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([3,3])
a

array([3, 3])

In [ ]:
b=np.zeros(4).reshape(2,2)
b

array([[0., 0.],
       [0., 0.]])

In [ ]:
c=np.ones(8).reshape(4,2)
c

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
d=np.identity(4).reshape(2,8)
d

array([[1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.]])

In [ ]:
np.full(4,8).reshape(2,2)

array([[8, 8],
       [8, 8]])

In [ ]:
np.full((7,7),7)

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [ ]:
np.empty((6,2))

array([[2.7039177e-316, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000]])

In [ ]:
np.arange(5,99,8)            

array([ 5, 13, 21, 29, 37, 45, 53, 61, 69, 77, 85, 93])

In [ ]:
np.linspace(5,99,8)   # Slicing the data

array([ 5.        , 18.42857143, 31.85714286, 45.28571429, 58.71428571,
       72.14285714, 85.57142857, 99.        ])

In [ ]:
np.random.rand(2,5,6)

array([[[0.79854185, 0.95586002, 0.79996663, 0.44224293, 0.05274772,
         0.89181611],
        [0.14100915, 0.09524906, 0.4881711 , 0.82960891, 0.81293879,
         0.78534765],
        [0.18686987, 0.98973501, 0.21430418, 0.36654881, 0.39916876,
         0.59816784],
        [0.92894807, 0.4176085 , 0.73888086, 0.14123616, 0.70798035,
         0.12893471],
        [0.21656702, 0.03421617, 0.59577756, 0.06769924, 0.10429742,
         0.74447081]],

       [[0.35378369, 0.42263852, 0.04523696, 0.46962162, 0.41843591,
         0.46539123],
        [0.4016833 , 0.3606278 , 0.33439776, 0.16491542, 0.92112243,
         0.55016086],
        [0.90992867, 0.88378585, 0.52209434, 0.66946398, 0.16153037,
         0.61019186],
        [0.28336536, 0.64324112, 0.02793776, 0.33050492, 0.38971089,
         0.68152417],
        [0.95299729, 0.11560936, 0.83431961, 0.30265715, 0.78569966,
         0.05247821]]])

In [ ]:
np.random.randint(3)

2

In [ ]:
c.ndim

2

In [ ]:
c.shape

(4, 2)

In [ ]:
c.dtype

dtype('float64')

In [ ]:
c.astype(np.float16).dtype

dtype('float16')

In [ ]:
c[:]=9756789
c

array([[9756789., 9756789.],
       [9756789., 9756789.],
       [9756789., 9756789.],
       [9756789., 9756789.]])

In [ ]:
c[:,1]=0
c

array([[9756789.,       0.],
       [9756789.,       0.],
       [9756789.,       0.],
       [9756789.,       0.]])

In [ ]:
a=[1,2,3]
b=[4,5,6]
c=np.concatenate((a,b))
c.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a=[1,2,3]
b=[4,5,6]
c=np.vstack((a,b))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d=c
d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a=[1,2,3]
b=[4,5,6]


In [ ]:
np.sort(a)

array([1, 2, 3])